name: {{ name }}
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  
  # State management
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  
  # Navigation
  auto_route: ^10.1.0+1
  auto_route_generator: ^10.0.1
  
  # Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Storage
  shared_preferences: ^2.2.2
  # isar: ^3.1.0+1
  # isar_flutter_libs: ^3.1.0+1
  
  # UI
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.0
  # flutter_screenutil: ^5.9.0
  lottie: ^3.3.1
  dotted_border: ^2.1.0
  shimmer: ^2.0.0
  flutter_expandable_fab: ^2.4.1
  # modal_bottom_sheet: ^3.0.0
  # pin_code_fields: ^8.0.1
  pinput: ^5.0.1
  smooth_page_indicator: ^1.2.1
  cached_network_image: ^3.4.1

  # Network
  dio: ^5.8.0+1
  url_launcher: ^6.3.1
  web_socket_channel: ^2.4.0
  connectivity_plus: 6.1.0
  network_info_plus: 6.1.1

  # Utils
  flutter_dotenv: ^5.2.1
  intl: ^0.19.0
  timeago: ^3.7.0
  uuid: 4.5.1
  money2: ^5.2.1
  faker: ^2.1.0
  device_info_plus: ^10.1.2
  path_provider: ^2.1.4
  mime: ^1.0.4

  # Maps
  mapbox_maps_flutter: ^2.7.0
  maps_launcher: ^3.0.0+1

  # Calendar
  syncfusion_flutter_calendar: ^29.1.40

  # File handling
  file_picker: ^10.1.2

  # Authentication
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  twitter_login: ^4.4.1
  sign_in_with_apple: ^6.1.4
  jwt_decoder: ^2.0.1

  # QR & Camera
  # qr_code_scanner_plus: ^2.0.7
  # qr_flutter: ^4.1.0
  # camera: ^0.10.0
  # permission_handler: ^11.3.1

  # Firebase
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^19.0.0

  # Others
  provider: ^6.0.0
  country_picker: ^2.0.27
  flutter_datetime_picker_plus: ^2.2.0
  sentry_flutter: ^8.14.0

dev_dependencies:
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.4.0
  flutter_intl: ^0.0.1
  intl_utils: ^2.8.3
  build_runner: ^2.4.15
  freezed: ^2.5.7
  # custom_lint: ^0.7.1
  # riverpod_generator: ^2.4.2
  # riverpod_lint: ^2.3.12
  # isar_generator: ^3.1.0+1
  flutter_launcher_icons: ^0.14.3


# FlutterGen configuration
flutter_gen:
  output: lib/generated/
  line_length: 80
  
  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#EBA116"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  adaptive_icon_monochrome: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/
    - assets/icons/
    - assets/socials/
    - shorebird.yaml
  #   - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist/Geist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Geist/Geist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Geist/Geist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Geist/Geist-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
